#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations



// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_SELECTED_PLAYER_INDEX = 0,
    FLOW_GLOBAL_VARIABLE_SELECTED_GAME_INDEX = 1,
    FLOW_GLOBAL_VARIABLE_SELECTED_GAME_ID = 2,
    FLOW_GLOBAL_VARIABLE_GAME_LABELS = 3,
    FLOW_GLOBAL_VARIABLE_GAME_IDS = 4,
    FLOW_GLOBAL_VARIABLE_GAME_LABELS_STR = 5,
    FLOW_GLOBAL_VARIABLE_OPTION_GAME_LABELS = 6,
    FLOW_GLOBAL_VARIABLE_OPTION_GAME_IDS = 7,
    FLOW_GLOBAL_VARIABLE_OPTION_BASE_INDICES = 8,
    FLOW_GLOBAL_VARIABLE_OPTION_GAME_LABELS_STR = 9,
    FLOW_GLOBAL_VARIABLE_OPTION_SELECTED_INDEX = 10,
    FLOW_GLOBAL_VARIABLE_ADMIN_TRIGGER = 11,
    FLOW_GLOBAL_VARIABLE_ADMIN_MODE = 12,
    FLOW_GLOBAL_VARIABLE_LICHTLOSER_ROUNDS_INDEX = 13,
    FLOW_GLOBAL_VARIABLE_LICHTLOSER_ROUNDS = 14,
    FLOW_GLOBAL_VARIABLE_JOKER_ENABLED = 15,
    FLOW_GLOBAL_VARIABLE_JOKER_COLOR_INDEX = 16,
    FLOW_GLOBAL_VARIABLE_JOKER_COLOR_LABELS = 17,
    FLOW_GLOBAL_VARIABLE_JOKER_COLOR_MODE_ID = 18,
    FLOW_GLOBAL_VARIABLE_JOKER_COLOR_MODE_IDS = 19,
    FLOW_GLOBAL_VARIABLE_PLAYER_COLOR_MODE_INDEX = 20,
    FLOW_GLOBAL_VARIABLE_PLAYER_COLOR_MODE_LABELS = 21,
    FLOW_GLOBAL_VARIABLE_PLAYER_COLOR_MODE_ID = 22,
    FLOW_GLOBAL_VARIABLE_PLAYER_COLOR_MODE_IDS = 23,
    FLOW_GLOBAL_VARIABLE_PLAYER_SINGLE_COLOR_INDEX = 24,
    FLOW_GLOBAL_VARIABLE_PLAYER_SINGLE_COLOR_LABELS = 25,
    FLOW_GLOBAL_VARIABLE_PLAYER_SINGLE_COLOR_ID = 26,
    FLOW_GLOBAL_VARIABLE_PLAYER_SINGLE_COLOR_IDS = 27,
    FLOW_GLOBAL_VARIABLE_PLAYER_OWN_COLOR_FLAG = 28,
    FLOW_GLOBAL_VARIABLE_INACTIVE_EFFECT_INDEX = 29,
    FLOW_GLOBAL_VARIABLE_INACTIVE_EFFECT_LABELS = 30,
    FLOW_GLOBAL_VARIABLE_INACTIVE_EFFECT_ID = 31,
    FLOW_GLOBAL_VARIABLE_INACTIVE_EFFECT_IDS = 32,
    FLOW_GLOBAL_VARIABLE_BORDER_COLOR_MODE_INDEX = 33,
    FLOW_GLOBAL_VARIABLE_BORDER_COLOR_MODE_LABELS = 34,
    FLOW_GLOBAL_VARIABLE_BORDER_COLOR_MODE_ID = 35,
    FLOW_GLOBAL_VARIABLE_BORDER_COLOR_MODE_IDS = 36,
    FLOW_GLOBAL_VARIABLE_BORDER_SINGLE_COLOR_INDEX = 37,
    FLOW_GLOBAL_VARIABLE_BORDER_SINGLE_COLOR_LABELS = 38,
    FLOW_GLOBAL_VARIABLE_BORDER_SINGLE_COLOR_ID = 39,
    FLOW_GLOBAL_VARIABLE_BORDER_SINGLE_COLOR_IDS = 40,
    FLOW_GLOBAL_VARIABLE_LED_GAME_BRIGHTNESS = 41,
    FLOW_GLOBAL_VARIABLE_LED_BORDER_BRIGHTNESS = 42,
    FLOW_GLOBAL_VARIABLE_LED_DISPLAY_BRIGHTNESS = 43,
    FLOW_GLOBAL_VARIABLE_IDLE_ENABLED = 44,
    FLOW_GLOBAL_VARIABLE_IDLE_TIMEOUT_INDEX = 45,
    FLOW_GLOBAL_VARIABLE_IDLE_TIMEOUT_ID = 46,
    FLOW_GLOBAL_VARIABLE_IDLE_TIMEOUT_MIN = 47,
    FLOW_GLOBAL_VARIABLE_IDLE_ENERGYSAVE = 48,
    FLOW_GLOBAL_VARIABLE_IDLE_TIMEOUT_LABELS = 49,
    FLOW_GLOBAL_VARIABLE_IDLE_TIMEOUT_IDS = 50,
    FLOW_GLOBAL_VARIABLE_IDLE_TIMEOUT_MINUTES = 51,
    FLOW_GLOBAL_VARIABLE_JOKER_FORCE_HIT_NEXT_ROUND = 52,
    FLOW_GLOBAL_VARIABLE_PERSIST_DIRTY = 53,
    FLOW_GLOBAL_VARIABLE_PLAYER_COUNT = 54,
    FLOW_GLOBAL_VARIABLE_DISPLAY_ID = 55,
    FLOW_GLOBAL_VARIABLE_MY_SEAT_INDEX = 56,
    FLOW_GLOBAL_VARIABLE_SEAT_USED = 57,
    FLOW_GLOBAL_VARIABLE_SCORE_P1 = 58,
    FLOW_GLOBAL_VARIABLE_SLOT_USED1 = 59,
    FLOW_GLOBAL_VARIABLE_SLOT_PLAYER1 = 60,
    FLOW_GLOBAL_VARIABLE_SCORE_P2 = 61,
    FLOW_GLOBAL_VARIABLE_SLOT_USED2 = 62,
    FLOW_GLOBAL_VARIABLE_SLOT_PLAYER2 = 63,
    FLOW_GLOBAL_VARIABLE_SCORE_P3 = 64,
    FLOW_GLOBAL_VARIABLE_SLOT_USED3 = 65,
    FLOW_GLOBAL_VARIABLE_SLOT_PLAYER3 = 66,
    FLOW_GLOBAL_VARIABLE_SCORE_P4 = 67,
    FLOW_GLOBAL_VARIABLE_SLOT_USED4 = 68,
    FLOW_GLOBAL_VARIABLE_SLOT_PLAYER4 = 69,
    FLOW_GLOBAL_VARIABLE_SCORE_P5 = 70,
    FLOW_GLOBAL_VARIABLE_SLOT_USED5 = 71,
    FLOW_GLOBAL_VARIABLE_SLOT_PLAYER5 = 72,
    FLOW_GLOBAL_VARIABLE_SCORE_P6 = 73,
    FLOW_GLOBAL_VARIABLE_SLOT_USED6 = 74,
    FLOW_GLOBAL_VARIABLE_SLOT_PLAYER6 = 75,
    FLOW_GLOBAL_VARIABLE_IS_MASTER_DISPLAY = 76,
    FLOW_GLOBAL_VARIABLE_GAME_OVER = 77,
    FLOW_GLOBAL_VARIABLE_IS_WINNER = 78,
    FLOW_GLOBAL_VARIABLE_WINNER_INDEX = 79,
    FLOW_GLOBAL_VARIABLE_IS_RESULT_PLAYER = 80,
    FLOW_GLOBAL_VARIABLE_RESULT_INDEX = 81,
    FLOW_GLOBAL_VARIABLE_MODE_WIN_LOSE = 82,
    FLOW_GLOBAL_VARIABLE_HIT_GROUP = 83,
    FLOW_GLOBAL_VARIABLE_HIT_TRIGGER = 84,
    FLOW_GLOBAL_VARIABLE_HIT_PLAYER_INDEX = 85,
    FLOW_GLOBAL_VARIABLE_JOKER_HIT = 86,
    FLOW_GLOBAL_VARIABLE_INFO_TEXT = 87,
    FLOW_GLOBAL_VARIABLE_INFO_VISIBLE = 88,
    FLOW_GLOBAL_VARIABLE_INFO_SEQ = 89,
    FLOW_GLOBAL_VARIABLE_LL_SHOW_BORDERS = 90,
    FLOW_GLOBAL_VARIABLE_LL_GAME_RUNNING = 91,
    FLOW_GLOBAL_VARIABLE_SPIN_IN_PROGRESS = 92,
    FLOW_GLOBAL_VARIABLE_CAN_START_SPIN = 93,
    FLOW_GLOBAL_VARIABLE_LAST_HIT_PLAYER = 94,
    FLOW_GLOBAL_VARIABLE_HIT_BLINK_ACTIVE = 95,
    FLOW_GLOBAL_VARIABLE_HIT_BLINK_PHASE = 96,
    FLOW_GLOBAL_VARIABLE_LL_ACCEL_TURNS_MIN10 = 97,
    FLOW_GLOBAL_VARIABLE_LL_ACCEL_TURNS_MAX10 = 98,
    FLOW_GLOBAL_VARIABLE_LL_DECEL_TURNS_MIN10 = 99,
    FLOW_GLOBAL_VARIABLE_LL_DECEL_TURNS_MAX10 = 100,
    FLOW_GLOBAL_VARIABLE_LL_MAX_SPEED_TURNS_MIN10 = 101,
    FLOW_GLOBAL_VARIABLE_LL_MAX_SPEED_TURNS_MAX10 = 102,
    FLOW_GLOBAL_VARIABLE_LL_STEP_MS = 103,
    FLOW_GLOBAL_VARIABLE_JOKER_ACTIVE = 104,
    FLOW_GLOBAL_VARIABLE_LAST_HIT_TRIGGER = 105,
    FLOW_GLOBAL_VARIABLE_PREVIEW_PLAYERS = 106,
    FLOW_GLOBAL_VARIABLE_PREVIEW_BORDERS = 107,
    FLOW_GLOBAL_VARIABLE_JOKER_DURATION_MS = 108,
    FLOW_GLOBAL_VARIABLE_FIRST_RUN = 109
};

// Native global variables



#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/