[env:ws-esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31-1/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
 
build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1

upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

board_build.flash_mode = dio
board_build.f_flash    = 80000000
board_build.partitions = custom_NOOTA.csv

lib_deps =
  lewisxhe/SensorLib@^0.2.6
  moononournation/GFX Library for Arduino @ 1.5.3

lib_ldf_mode = chain+